language: ruby
rvm:
  - 2.6.6
addons:
  postgresql: "9.6"
  chrome: stable
  apt:
    sources:
    - sourceline: "ppa:mc3man/trusty-media"
    packages:
      - libvips-tools
      - ffmpeg
services:
  - postgresql
cache:
  bundler: true
  directories:
    - /home/travis/.rvm/
    - ./tmp/solr_dist
before_install:
  - gem install bundler
  - nvm install node
before_script:
  - psql -c 'create database scihist_digicoll_test;' -U postgres
  - yarn install
